fail_fast: true

repos:
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        description: "Run 'mypy' for static type checking"
        entry: mypy
        language: python
        types: [ python ]
        args: [ ]
        stages: [ pre-commit ]

    -   id: ruff
        name: ruff
        description: "Run 'ruff' for linting Python code at high speed"
        entry: ruff check --force-exclude --fix
        language: python
        types_or: [ python, pyi ]
        args: [ ]
        require_serial: true
        stages: [ pre-commit ]

    -   id: ruff-format
        name: ruff-format
        description: "Format Python files using 'ruff format' for consistency"
        entry: ruff format --force-exclude
        language: system
        types_or: [ python, pyi ]
        args: [ ]
        require_serial: true
        stages: [ pre-commit ]
