name: project-template

channels:
  - conda-forge

dependencies:
  - conda-lock
  - invoke
  - mypy
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.10
  - ruff

variables:
  PYTHONPATH:
    - ./source/python
  MYPYPATH:
    - ./source/python
